/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ltp3.trabalhoFinal.interfaceUsuario;

import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CampusDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CursoAreaDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CursoDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.Campus;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.CursoArea;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaisaContijo
 */
public class ifrmCursoCad extends javax.swing.JInternalFrame {
    CursoArea curso;
    CursoDAO cursoDao = new CursoDAO();
    /**
     * Creates new form ifrmCampusCad
     */
    public ifrmCursoCad() throws SQLException {
        initComponents();
        
        List<CursoArea> lista = cursoDao.ListarTodos();
        
        preencheTabela(lista);
    }
    
    private void preencheTabela(List<CursoArea> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Curso");
        model.addColumn("Sigla");
     
        for (CursoArea ca : lista) {
            Vector valores = new Vector();
            valores.add(0,ca.getIdCursoArea());
            valores.add(1,ca.getNome());
            valores.add(2,ca.getSigla());
     
            model.addRow(valores);
        }
        jtbListarCurso.setModel(model);
        jtbListarCurso.repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCursoCadNome = new javax.swing.JTextField();
        btnCursoCadSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListarCurso = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblSigla = new javax.swing.JLabel();
        txtCursoCadSigla = new javax.swing.JTextField();
        btnEditarCurso = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));

        lblCurso.setText("Nome");

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnCursoCadSalvar.setText("Salvar");
        btnCursoCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoCadSalvarActionPerformed(evt);
            }
        });

        jtbListarCurso.setBackground(new java.awt.Color(102, 204, 0));
        jtbListarCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbListarCurso);

        lblTitulo.setText("Curso");

        lblSigla.setText("Sigla");

        btnEditarCurso.setText("Editar");
        btnEditarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCursoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCursoCadNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSigla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoCadSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCursoCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btnEditarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblTitulo)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCursoCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSigla)
                    .addComponent(txtCursoCadSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCursoCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(285, 285, 285))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursoCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoCadSalvarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente salvar esses dados?")==0){
            
             try {
                curso = new CursoArea();
                curso.setNome(txtCursoCadNome.getText());
                curso.setSigla(txtCursoCadSigla.getText());
                //----
               
                try {
                    if(cursoDao.Salvar(curso)){
                        JOptionPane.showMessageDialog(rootPane, "Dados foram salvos com sucesso.");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ifrmAlunoCad.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                txtCursoCadNome.setText(null);
                txtCursoCadSigla.setText(null);
                
                List<CursoArea> lista = cursoDao.ListarTodos();

                preencheTabela(lista);
            } catch (SQLException ex) {
                Logger.getLogger(ifrmCursoAreaCad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados, consulte o administrador do sistema.");
        }
    }//GEN-LAST:event_btnCursoCadSalvarActionPerformed

    private void btnEditarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCursoActionPerformed
        try {
            // TODO add your handling code here:
            Object valor = jtbListarCurso.getValueAt( jtbListarCurso.getSelectedRow(), 0);
            
             CursoArea ca = null;
                
                ca = cursoDao.Abrir((int)valor);
                ifrmCursoEdit janela = new ifrmCursoEdit(ca, cursoDao);
                this.getParent().add(janela);
                janela.setVisible(true);
                this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ifrmCursoCad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditarCursoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        Object valor = jtbListarCurso.getValueAt( jtbListarCurso.getSelectedRow(), 0);
      
       
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente apagar este curso?") == 0) {
            try {                
                if (cursoDao.Apagar((int)valor)) {
                    JOptionPane.showMessageDialog(rootPane, "Curso deletado com sucesso!");  
                    preencheTabela(cursoDao.ListarTodos());
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao apagar! Consulte o administrador do sistema!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ifrmCursoCad.class.getName()).log(Level.SEVERE, null, ex);
            }

            } else {                
                JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            }
       
    }//GEN-LAST:event_btnDeletarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursoCadSalvar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditarCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbListarCurso;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCursoCadNome;
    private javax.swing.JTextField txtCursoCadSigla;
    // End of variables declaration//GEN-END:variables
}
