/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ltp3.trabalhoFinal.interfaceUsuario;

import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CampusDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CursoAreaDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CursoDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.Campus;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.CursoArea;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaisaContijo
 */
public class ifrmCursoCad extends javax.swing.JInternalFrame {
    CursoArea curso;
    CursoDAO cursoDao = new CursoDAO();
    /**
     * Creates new form ifrmCampusCad
     */
    public ifrmCursoCad() throws SQLException {
        initComponents();
        
        List<CursoArea> lista = cursoDao.ListarTodos();
        
        preencheTabela(lista);
    }
    
    private void preencheTabela(List<CursoArea> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Curso");
        model.addColumn("Sigla");
     
        for (CursoArea ca : lista) {
            Vector valores = new Vector();
            valores.add(0,ca.getIdCursoArea());
            valores.add(1,ca.getNome());
            valores.add(2,ca.getSigla());
     
            model.addRow(valores);
        }
        jtbListarCurso.setModel(model);
        jtbListarCurso.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCursoCadNome = new javax.swing.JTextField();
        btnCursoCadSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListarCurso = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSigla = new javax.swing.JLabel();
        txtCursoCadSigla = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        lblCurso.setText("Nome");

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnCursoCadSalvar.setText("Salvar");
        btnCursoCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoCadSalvarActionPerformed(evt);
            }
        });

        jtbListarCurso.setBackground(new java.awt.Color(102, 204, 0));
        jtbListarCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbListarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListarCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListarCurso);

        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Curso");

        jLabel4.setText("Clique sobre um item para Editar ou Excluir");

        lblSigla.setText("Sigla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSigla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoCadSigla)
                                .addGap(18, 18, 18)
                                .addComponent(btnCursoCadSalvar)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lblTitulo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCursoCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCursoCadSalvar)
                    .addComponent(lblSigla)
                    .addComponent(txtCursoCadSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursoCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoCadSalvarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente salvar esses dados?")==0){
            
             try {
                curso = new CursoArea();
                curso.setNome(txtCursoCadNome.getText());
                curso.setSigla(txtCursoCadSigla.getText());
                //----
               
                try {
                    if(cursoDao.Salvar(curso)){
                        JOptionPane.showMessageDialog(rootPane, "Dados foram salvos com sucesso.");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ifrmAlunoCad.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                txtCursoCadNome.setText(null);
                txtCursoCadSigla.setText(null);
                
                List<CursoArea> lista = cursoDao.ListarTodos();

                preencheTabela(lista);
            } catch (SQLException ex) {
                Logger.getLogger(ifrmCursoAreaCad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados, consulte o administrador do sistema.");
        }
    }//GEN-LAST:event_btnCursoCadSalvarActionPerformed

    private void jtbListarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListarCursoMouseClicked
        try {
            // TODO add your handling code here:
            Object valor = jtbListarCurso.getValueAt( jtbListarCurso.getSelectedRow(), 0);
            CursoArea ca = null;
            
            ca = cursoDao.Abrir((int)valor);
            ifrmCursoEdit janela = new ifrmCursoEdit(ca, cursoDao);
            this.getParent().add(janela);
            janela.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ifrmCursoAreaCad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jtbListarCursoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursoCadSalvar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbListarCurso;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCursoCadNome;
    private javax.swing.JTextField txtCursoCadSigla;
    // End of variables declaration//GEN-END:variables
}
