/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ltp3.trabalhoFinal.interfaceUsuario;

import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.OrientadorDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.Cidade;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.Orientador;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author emerson
 */
public class ifrmOrientadorListar extends javax.swing.JInternalFrame {
    
    OrientadorDAO odao;
    
    
   
    /**
     * Creates new form frmListarProduto
     */
    public ifrmOrientadorListar() throws SQLException {
        initComponents();
        
        odao = new OrientadorDAO();
        
        List<Orientador> orientador = odao.ListarTodos();

        preencheTabela(orientador);
        

    }
    
    //Metodo para listar Produtos na Tabela tblListagemProd
    private void preencheTabela(List<Orientador> lista) {
        Cidade cidade = new Cidade();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("SIAPE");
        model.addColumn("NOME");
        model.addColumn("RG");
        model.addColumn("CFP");
        model.addColumn("NASCIMENTO");
        model.addColumn("NACIONALIDADE");
        model.addColumn("TITULAÇÃO");
        model.addColumn("FORMAÇÃO");

        for (Orientador o : lista) {
            Vector valores = new Vector();
            valores.add(0,o.getIdOrientador());
            valores.add(1,o.getMatriculaSiape());
            valores.add(2,o.getNome());
            valores.add(3,o.getRg());
            valores.add(4,o.getCpf());
            valores.add(5,o.getDataNascimento());
            valores.add(6,o.getPessoaNacionalidade().getNome());
            valores.add(7,o.getTituloAcademico());
            valores.add(8,o.getFormacaoUniversitaria());
            model.addRow(valores);
        }
        tblListagemOrientador.setModel(model);
        tblListagemOrientador.repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeOrientador = new javax.swing.JLabel();
        txtFiltrarC = new javax.swing.JTextField();
        btnFiltrarOrientador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemOrientador = new javax.swing.JTable();
        jpTituloProdutoListar = new javax.swing.JPanel();
        lblTituloOrientadorListar = new javax.swing.JLabel();
        jpRemoverItemtbEndereco = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 420));

        lblNomeOrientador.setText("Nome");

        btnFiltrarOrientador.setText("Filtrar");
        btnFiltrarOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarOrientadorActionPerformed(evt);
            }
        });

        tblListagemOrientador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListagemOrientador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemOrientadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagemOrientador);

        jpTituloProdutoListar.setBackground(new java.awt.Color(102, 204, 0));

        lblTituloOrientadorListar.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lblTituloOrientadorListar.setText("Orientadores");

        javax.swing.GroupLayout jpTituloProdutoListarLayout = new javax.swing.GroupLayout(jpTituloProdutoListar);
        jpTituloProdutoListar.setLayout(jpTituloProdutoListarLayout);
        jpTituloProdutoListarLayout.setHorizontalGroup(
            jpTituloProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloProdutoListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloOrientadorListar)
                .addGap(337, 337, 337))
        );
        jpTituloProdutoListarLayout.setVerticalGroup(
            jpTituloProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloProdutoListarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloOrientadorListar)
                .addGap(19, 19, 19))
        );

        jpRemoverItemtbEndereco.setBackground(new java.awt.Color(102, 204, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText("Clique sobre algum campo para ver versão FULL ");

        javax.swing.GroupLayout jpRemoverItemtbEnderecoLayout = new javax.swing.GroupLayout(jpRemoverItemtbEndereco);
        jpRemoverItemtbEndereco.setLayout(jpRemoverItemtbEnderecoLayout);
        jpRemoverItemtbEnderecoLayout.setHorizontalGroup(
            jpRemoverItemtbEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRemoverItemtbEnderecoLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel3)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jpRemoverItemtbEnderecoLayout.setVerticalGroup(
            jpRemoverItemtbEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRemoverItemtbEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloProdutoListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeOrientador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrarOrientador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpRemoverItemtbEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloProdutoListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeOrientador)
                    .addComponent(btnFiltrarOrientador))
                .addGap(18, 18, 18)
                .addComponent(jpRemoverItemtbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarOrientadorActionPerformed
  
    }//GEN-LAST:event_btnFiltrarOrientadorActionPerformed

    private void tblListagemOrientadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemOrientadorMouseClicked

        ifrmlistarOrientadorFull janela = new ifrmlistarOrientadorFull();
        add(janela);
        janela.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_tblListagemOrientadorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarOrientador;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpRemoverItemtbEndereco;
    private javax.swing.JPanel jpTituloProdutoListar;
    private javax.swing.JLabel lblNomeOrientador;
    private javax.swing.JLabel lblTituloOrientadorListar;
    private javax.swing.JTable tblListagemOrientador;
    private javax.swing.JTextField txtFiltrarC;
    // End of variables declaration//GEN-END:variables
}
