/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ltp3.trabalhoFinal.interfaceUsuario;

import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CampusDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.dataAccess.CursoAreaDAO;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.Campus;
import br.edu.ifnmg.ltp3.trabalhoFinal.domainModel.CursoArea;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaisaContijo
 */
public class ifrmCursoAreaCad extends javax.swing.JInternalFrame {
    CursoArea curso;
    CursoAreaDAO cursoDao = new CursoAreaDAO();
    /**
     * Creates new form ifrmCampusCad
     */
    public ifrmCursoAreaCad() throws SQLException {
        initComponents();
        
        List<CursoArea> lista = cursoDao.ListarTodos();
        
        preencheTabela(lista);
    }
    
    private void preencheTabela(List<CursoArea> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Curso");
        model.addColumn("Sigla");
     
        for (CursoArea ca : lista) {
            Vector valores = new Vector();
            valores.add(0,ca.getIdCursoArea());
            valores.add(1,ca.getNome());
            valores.add(2,ca.getSigla());
     
            model.addRow(valores);
        }
        jtbListarCursoArea.setModel(model);
        jtbListarCursoArea.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCursoArea = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCursoAreaCadNome = new javax.swing.JTextField();
        btnCursoAreaCadSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListarCursoArea = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCursoAreaCadSigla = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        lblCursoArea.setText("Nome");

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnCursoAreaCadSalvar.setText("Salvar");
        btnCursoAreaCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoAreaCadSalvarActionPerformed(evt);
            }
        });

        jtbListarCursoArea.setBackground(new java.awt.Color(102, 204, 0));
        jtbListarCursoArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbListarCursoArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListarCursoAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListarCursoArea);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Curso/Area");

        jLabel4.setText("Clique sobre um item para Editar ou Excluir");

        jLabel1.setText("Sigla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCursoArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoAreaCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCursoAreaCadSigla)
                                .addGap(18, 18, 18)
                                .addComponent(btnCursoAreaCadSalvar)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCursoArea)
                    .addComponent(txtCursoAreaCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCursoAreaCadSalvar)
                    .addComponent(jLabel1)
                    .addComponent(txtCursoAreaCadSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursoAreaCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoAreaCadSalvarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente salvar esses dados?")==0){
            
             try {
                curso = new CursoArea();
                curso.setNome(txtCursoAreaCadNome.getText());
                curso.setSigla(txtCursoAreaCadSigla.getText());
                //----
               
                try {
                    if(cursoDao.Salvar(curso)){
                        JOptionPane.showMessageDialog(rootPane, "Dados foram salvos com sucesso.");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ifrmAlunoCad.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                txtCursoAreaCadNome.setText(null);
                txtCursoAreaCadSigla.setText(null);
                
                List<CursoArea> lista = cursoDao.ListarTodos();

                preencheTabela(lista);
            } catch (SQLException ex) {
                Logger.getLogger(ifrmCursoAreaCad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao salvar os dados, consulte o administrador do sistema.");
        }
    }//GEN-LAST:event_btnCursoAreaCadSalvarActionPerformed

    private void jtbListarCursoAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListarCursoAreaMouseClicked
        try {
            // TODO add your handling code here:
            Object valor = jtbListarCursoArea.getValueAt( jtbListarCursoArea.getSelectedRow(), 0);
            CursoArea ca = null;
            
            ca = cursoDao.Abrir((int)valor);
            ifrmCursoAreaEdit janela = new ifrmCursoAreaEdit(ca, cursoDao);
            this.getParent().add(janela);
            janela.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ifrmCursoAreaCad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jtbListarCursoAreaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursoAreaCadSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbListarCursoArea;
    private javax.swing.JLabel lblCursoArea;
    private javax.swing.JTextField txtCursoAreaCadNome;
    private javax.swing.JTextField txtCursoAreaCadSigla;
    // End of variables declaration//GEN-END:variables
}
